/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ZCSD_SHIPTO_PARTNERSObjectPageObjectPage journey");

        opaTest("Navigate to ZCSD_SHIPTO_PARTNERSObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheZCSD_SHIPTO_PARTNERSList.onFilterBar().iExecuteSearch();

            Then.onTheZCSD_SHIPTO_PARTNERSList.onTable().iCheckRows();
            When.onTheZCSD_SHIPTO_PARTNERSList.onTable().iPressRow(0);

            Then.onTheZCSD_SHIPTO_PARTNERSObjectPage.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheZCSD_SHIPTO_PARTNERSObjectPage.iCheckSection({ section: "GeneralInfo" });
            Then.onTheZCSD_SHIPTO_PARTNERSObjectPage.onForm({ section: "GeneralInfo" }).iCheckField({ property: "Shipto" });
            Then.onTheZCSD_SHIPTO_PARTNERSObjectPage.onForm({ section: "GeneralInfo" }).iCheckField({ property: "Customer" });
            Then.onTheZCSD_SHIPTO_PARTNERSObjectPage.onForm({ section: "GeneralInfo" }).iCheckField({ property: "PreviousAccount" });
            Then.onTheZCSD_SHIPTO_PARTNERSObjectPage.onForm({ section: "GeneralInfo" }).iCheckField({ property: "CustomerAddress" });
            Then.onTheZCSD_SHIPTO_PARTNERSObjectPage.onForm({ section: "GeneralInfo" }).iCheckField({ property: "SalesLead" });
            Then.onTheZCSD_SHIPTO_PARTNERSObjectPage.onForm({ section: "GeneralInfo" }).iCheckField({ property: "SalesSupport" });
            Then.onTheZCSD_SHIPTO_PARTNERSObjectPage.onForm({ section: "GeneralInfo" }).iCheckField({ property: "ShiptoName" });
            Then.onTheZCSD_SHIPTO_PARTNERSObjectPage.onForm({ section: "GeneralInfo" }).iCheckField({ property: "SalesLeadName" });
            Then.onTheZCSD_SHIPTO_PARTNERSObjectPage.onForm({ section: "GeneralInfo" }).iCheckField({ property: "SalesSupportName" });
            Then.onTheZCSD_SHIPTO_PARTNERSObjectPage.onForm({ section: "GeneralInfo" }).iCheckField({ property: "CustomerHiearchyL1" });
            Then.onTheZCSD_SHIPTO_PARTNERSObjectPage.onForm({ section: "GeneralInfo" }).iCheckField({ property: "CustomerHiearchyL2" });
            Then.onTheZCSD_SHIPTO_PARTNERSObjectPage.onForm({ section: "GeneralInfo" }).iCheckField({ property: "CustomerHiearchyL3" });
            Then.onTheZCSD_SHIPTO_PARTNERSObjectPage.onForm({ section: "GeneralInfo" }).iCheckField({ property: "CustomerHiearchyL3Name" });
            Then.onTheZCSD_SHIPTO_PARTNERSObjectPage.onForm({ section: "GeneralInfo" }).iCheckField({ property: "CustomerHiearchyL2Name" });
            Then.onTheZCSD_SHIPTO_PARTNERSObjectPage.onForm({ section: "GeneralInfo" }).iCheckField({ property: "CustomerHiearchyL1Name" });
            Then.onTheZCSD_SHIPTO_PARTNERSObjectPage.onForm({ section: "GeneralInfo" }).iCheckField({ property: "selectflag" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});