/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ZCSD_SHIPTO_PARTNERSListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheZCSD_SHIPTO_PARTNERSList.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheZCSD_SHIPTO_PARTNERSList.onFilterBar().iCheckFilterField("Sales Organization");
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheZCSD_SHIPTO_PARTNERSList.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheZCSD_SHIPTO_PARTNERSList.onFilterBar().iExecuteSearch();
        //     Then.onTheZCSD_SHIPTO_PARTNERSList.onTable().iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheZCSD_SHIPTO_PARTNERSList.onTable().iCheckCreate({ visible: true });
            // Then.ontheZCSD_SHIPTO_PARTNERSList.onTable().iPressCreate();
            // Then.onTheZCSD_SHIPTO_PARTNERSList.onTable().iPressAction("Sales Support");
            Then.onTheZCSD_SHIPTO_PARTNERSList.onTable().iCheckAction("Sales Support", { enabled: false });
            Then.onTheZCSD_SHIPTO_PARTNERSList.onTable().iCheckColumns(undefined, {"Shipto":{"header":"Shipto"},"Customer":{"header":"Customer"},"ParentShipto":{"header":"Parent Shipto"},"PreviousAccount":{"header":"Previous Account"},"SalesLead":{"header":"Sales Lead"},"CustomerAddress":{"header":"Customer Address"},"SalesSupport":{"header":"Sales Support"},"ShiptoName":{"header":"Shipto Name"},"SalesLeadName":{"header":"Sales Lead Name"},"SalesSupportName":{"header":"Sales Support Name"},"CustomerHiearchyL1":{"header":"Customer Hiearchy L1"},"CustomerHiearchyL2":{"header":"Customer Hiearchy L2"},"CustomerHiearchyL3":{"header":"Customer Hiearchy L3"},"CustomerHiearchyL3Name":{"header":"Customer Hiearchy L1 Name"},"CustomerHiearchyL2Name":{"header":"Customer Hiearchy L2 Name"},"CustomerHiearchyL1Name":{"header":"Customer Hiearchy L3 Name"},"selectflag":{"header":"Select"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheZCSD_SHIPTO_PARTNERSList.onFilterBar().iExecuteSearch();
            
            Then.onTheZCSD_SHIPTO_PARTNERSList.onTable().iCheckRows();

            When.onTheZCSD_SHIPTO_PARTNERSList.onTable().iPressRow(0);
            Then.onTheZCSD_SHIPTO_PARTNERSObjectPage.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});